In [13]:
#Question1
import numpy as np
a=np.array([1,2,3,4])
pw=4
n_inc=np.column_stack([a**(pw-1-i) for i in range(pw)])
inc=np.array([a**(i) for i in range(pw)])
print("Matrix in decreasing order of power\n\n",n_inc,"\n")
print("Matrix in increasing order of power\n\n",inc)

Matrix in decreasing order of power

 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]] 

Matrix in increasing order of power

 [[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  4  9 16]
 [ 1  8 27 64]]


In [22]:
#Question2
x=[3,5,7,2,8,10,11,65,72,81,99,100,150]
n=3
sum1=0
s=0
y=np.array(x)
y_sum=np.cumsum(y,dtype=float)
y_sum[n:]=y_sum[n:]-y_sum[:-n]
print((y_sum[n-1:]/n).round(2))

[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
